### ISSUE TITLE
 It always highlight the wrong words when using find all reference.

### ISSUE THREAD

**Issue by suzukajiang** [jaycetyle/vscode-gnu-global#6]
It always highlight the wrong words when using find all reference.

VSCODE version : 1.34.0
window7
gnu global version : 6.6.3

**Comment by xxyyttxx** [comment]
![image](https://user-images.githubusercontent.com/25104011/62384943-3e7aef80-b586-11e9-9607-de5ba7e03058.png)

The problem happen at the line with white space indent.

VSCODE Version 1.36.1 (1.36.1)
macOS 10.14.3 (18D109)
global (GNU GLOBAL) 6.6.3

**Comment by jaycetyle** [comment]
Many thanks for your report. I'm trying to reproduce this issue.

**Comment by jaycetyle** [comment]
I've fixed it in 0.2.9. Please have a try.

**Comment by suzukajiang** [comment]
I have tried the latest version, but the problem still exist.
[图像]




获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jaycetyle** [comment]
Sorry, I think it still wrong if the line starts with more than one white spaces. If this is true, I'll try to fix it.
The root cause is gnu global uses spaces to seperate different tokens and the white spaces are removed while spliting these tokens.

**Comment by jaycetyle** [comment]
There's still one issue about this bug. The highlighter finds the first matched string in target line and highlights it. If this line contains two strings for the target symbol, it always highlights the first one and it may not be the one that we really want.

![image](https://user-images.githubusercontent.com/29505542/63074387-aa366280-bf5f-11e9-9966-ddb14cdc9e8b.png)

We'll need a better scanner to parse the target line and find the token that we really want.

**Comment by xxyyttxx** [comment]
It's really an annoying matter to deal with token.

Doesn't Global generates the column position of the symbol?

**Comment by jaycetyle** [comment]
Unfortunately not. We have to do it ourselves.
